// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/CycleZero/Reimbee/infra"
	"github.com/CycleZero/Reimbee/internal/domain"
	"github.com/CycleZero/Reimbee/internal/domain/agent"
	"github.com/CycleZero/Reimbee/internal/domain/agent/tools"
	"github.com/CycleZero/Reimbee/internal/domain/approval"
	"github.com/CycleZero/Reimbee/internal/domain/auth"
	"github.com/CycleZero/Reimbee/internal/domain/budget"
	"github.com/CycleZero/Reimbee/internal/domain/compliance"
	"github.com/CycleZero/Reimbee/internal/domain/department"
	"github.com/CycleZero/Reimbee/internal/domain/employee"
	"github.com/CycleZero/Reimbee/internal/domain/reimbursement"
	"github.com/CycleZero/Reimbee/internal/router"
	"github.com/CycleZero/Reimbee/log"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func initApp(vc *viper.Viper, logger *log.Logger) *MainApp {
	client := infra.NewRedisClient(vc)
	redisClient := infra.NewCustomRedisClient(client)
	data := infra.NewData(vc, redisClient)
	employeeRepo := auth.NewEmployeeRepo(data)
	authBiz := auth.NewAuthBiz(logger, employeeRepo, vc)
	authService := auth.NewAuthService(authBiz, logger)
	modelProvider := agent.MustNewModel(vc, logger)
	ocrRecognizer := infra.MustNewOCRRecognizer(vc)
	fileStorage := infra.MustNewFileStorage(vc)
	db := infra.GetDB(data)
	redisSessionCache := infra.NewRedisSessionCache(redisClient)
	sessionRepo := infra.NewSessionRepo(db, redisSessionCache, logger)
	receiptRepo := reimbursement.NewReceiptRepo(data)
	ocrTool := tools.NewOCRTool(ocrRecognizer, fileStorage, sessionRepo, receiptRepo, logger)
	budgetRepo := budget.NewBudgetRepo(data)
	budgetBiz := budget.NewBudgetBiz(logger, budgetRepo)
	budgetTool := tools.NewBudgetTool(budgetBiz, sessionRepo, logger)
	gofpdfPDFGenerator := infra.NewGofpdfPDFGenerator(logger)
	reimbursementRepo := reimbursement.NewReimbursementRepo(data)
	itemRepo := reimbursement.NewItemRepo(data)
	itemBiz := reimbursement.NewItemBiz(logger, itemRepo)
	approvalRepo := approval.NewApprovalRepo(data)
	approvalBiz := approval.NewApprovalBiz(logger, approvalRepo)
	employeeEmployeeRepo := employee.NewEmployeeRepo(data)
	employeeBiz := employee.NewEmployeeBiz(logger, employeeEmployeeRepo)
	reimbursementBiz := reimbursement.NewReimbursementBiz(logger, reimbursementRepo, itemBiz, receiptRepo, budgetBiz, approvalBiz, employeeBiz)
	pdfTool := tools.NewPDFTool(gofpdfPDFGenerator, fileStorage, reimbursementBiz, logger)
	smtpEmailSender := infra.NewSMTPEmailSender(vc, logger)
	emailTool := tools.NewEmailTool(smtpEmailSender, reimbursementBiz, logger)
	progressTool := tools.NewProgressTool(reimbursementBiz, approvalBiz, logger)
	queryTool := tools.NewQueryTool(reimbursementBiz, logger)
	departmentRepo := department.NewDepartmentRepo(data)
	departmentBiz := department.NewDepartmentBiz(logger, departmentRepo)
	searchDepartmentTool := tools.NewSearchDepartmentTool(departmentBiz, logger)
	searchEmployeeTool := tools.NewSearchEmployeeTool(employeeBiz, logger)
	embedder := infra.MustNewEmbedder(vc, logger)
	vectorStore := infra.MustNewVectorStore(vc, embedder, logger)
	knowledgeBase := compliance.NewKnowledgeBase(data, embedder, vectorStore, logger)
	searchPolicyTool := tools.NewSearchPolicyTool(knowledgeBase, logger)
	complianceAgentTool := tools.NewComplianceAgentTool(modelProvider, searchPolicyTool, logger)
	createReimbTool := tools.NewCreateReimbTool(reimbursementBiz, sessionRepo, logger)
	submitReimbTool := tools.NewSubmitReimbTool(reimbursementBiz, sessionRepo, logger)
	approveTool := tools.NewApproveTool(reimbursementBiz, logger)
	rejectTool := tools.NewRejectTool(reimbursementBiz, logger)
	pendingTool := tools.NewPendingTool(reimbursementBiz, logger)
	cancelReimbTool := tools.NewCancelReimbTool(reimbursementBiz, logger)
	deptTool := tools.NewDeptTool(employeeBiz, logger)
	reimbDetailTool := tools.NewReimbDetailTool(reimbursementBiz, logger)
	testInterruptTool := tools.NewTestInterruptTool()
	organizeItemsTool := tools.NewOrganizeItemsTool(itemRepo, receiptRepo, sessionRepo, logger)
	listInvoicesTool := tools.NewListInvoicesTool(sessionRepo, logger)
	checkDeadlineTool := tools.NewCheckDeadlineTool(sessionRepo, logger)
	toolSet := tools.NewToolSet(ocrTool, budgetTool, pdfTool, emailTool, progressTool, queryTool, searchDepartmentTool, searchEmployeeTool, searchPolicyTool, complianceAgentTool, createReimbTool, submitReimbTool, approveTool, rejectTool, pendingTool, cancelReimbTool, deptTool, reimbDetailTool, testInterruptTool, organizeItemsTool, listInvoicesTool, checkDeadlineTool, logger)
	config := agent.DefaultConfig()
	reimburseAgent := agent.NewReimburseAgent(modelProvider, toolSet, sessionRepo, config, logger)
	agentService := agent.NewAgentService(reimburseAgent, sessionRepo, logger)
	departmentService := department.NewDepartmentService(departmentBiz, logger)
	employeeService := employee.NewEmployeeService(employeeBiz, logger)
	budgetService := budget.NewBudgetService(budgetBiz, logger)
	approvalService := approval.NewApprovalService(approvalBiz, logger)
	reimbursementService := reimbursement.NewReimbursementService(reimbursementBiz, approvalBiz, fileStorage, logger)
	complianceBiz := compliance.NewComplianceBiz(logger, knowledgeBase)
	policyRepo := compliance.NewPolicyRepo(data)
	complianceService := compliance.NewComplianceService(complianceBiz, knowledgeBase, policyRepo, logger)
	serviceHub := domain.NewServiceHub(authService, agentService, departmentService, employeeService, budgetService, approvalService, reimbursementService, complianceService)
	registerFunc := router.NewRegisterFunc()
	registeredMiddleWire := router.NewRegisterMiddleWire(vc)
	mainApp := NewMainApp(vc, serviceHub, registerFunc, registeredMiddleWire, data)
	return mainApp
}
